+ source /home/mugen/libs/locallibs/common_lib.sh
++ python3 --version
Python 3.11.6
++ source /home/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Mon Dec 23 06:58:47 2024 - INFO  - Start to prepare the test environment.
++ uname -r
+ DNF_INSTALL 'kmod kernel-6.6.0-72.0.0.76.oe2403sp1.riscv64'
+ pkgs='kmod kernel-6.6.0-72.0.0.76.oe2403sp1.riscv64'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /home/mugen/libs/locallibs/rpm_manage.py install --pkgs 'kmod kernel-6.6.0-72.0.0.76.oe2403sp1.riscv64' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp5jqotrka
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp5jqotrka
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Mon Dec 23 07:09:09 2024 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon Dec 23 07:09:09 2024 - INFO  - Start to run test.
+ lsmod
+ grep ipvlan
+ CHECK_RESULT 1 1 0 'ipvlan is not loaded: failed!'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='ipvlan is not loaded: failed!'
+ exit_mode=0
+ '[' -z '1 1 0 ipvlan is not loaded: failed!' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ modprobe ipvlan
modprobe: ERROR: could not insert 'ipvlan': Invalid argument
+ CHECK_RESULT 1 0 0 'Modprobe ipvlan: failed!'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Modprobe ipvlan: failed!'
+ exit_mode=0
+ '[' -z '1 0 0 Modprobe ipvlan: failed!' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Modprobe ipvlan: failed!'
+ LOG_ERROR 'Modprobe ipvlan: failed!'
+ message='Modprobe ipvlan: failed!'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level error --message 'Modprobe ipvlan: failed!'
Mon Dec 23 07:09:10 2024 - ERROR - Modprobe ipvlan: failed!
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_IPVLAN_07.sh line 32'
+ message='oe_test_IPVLAN_07.sh line 32'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_IPVLAN_07.sh line 32'
Mon Dec 23 07:09:10 2024 - ERROR - oe_test_IPVLAN_07.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ lsmod
+ grep ipvlan
+ CHECK_RESULT 1 0 0 'Load ipvlan: failed!'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Load ipvlan: failed!'
+ exit_mode=0
+ '[' -z '1 0 0 Load ipvlan: failed!' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Load ipvlan: failed!'
+ LOG_ERROR 'Load ipvlan: failed!'
+ message='Load ipvlan: failed!'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level error --message 'Load ipvlan: failed!'
Mon Dec 23 07:09:11 2024 - ERROR - Load ipvlan: failed!
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_IPVLAN_07.sh line 34'
+ message='oe_test_IPVLAN_07.sh line 34'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_IPVLAN_07.sh line 34'
Mon Dec 23 07:09:11 2024 - ERROR - oe_test_IPVLAN_07.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ modinfo ipvlan
+ grep -E 'filename|alias|description|author|license|srcversion|depends|retpoline|intree|name|vermagic|sig_id|signer|sig_key|sig_hashalgo|signature'
filename:       /lib/modules/6.6.0-72.0.0.76.oe2403sp1.riscv64/kernel/drivers/net/ipvlan/ipvlan.ko.xz
alias:          rtnl-link-ipvlan
description:    Driver for L3 (IPv6/IPv4) based VLANs
author:         Mahesh Bandewar <maheshb@google.com>
license:        GPL
srcversion:     E165E1FFE36F939229D2C87
depends:        
intree:         Y
name:           ipvlan
vermagic:       6.6.0-72.0.0.76.oe2403sp1.riscv64 SMP preempt mod_unload modversions riscv
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        5C:F2:07:92:4E:CA:1C:9C:28:D2:03:CB:00:20:BC:06:40:68:98:9C
sig_hashalgo:   sha256
signature:      B4:AE:34:E3:2D:BB:B8:93:64:68:C1:58:6E:70:D4:07:97:60:8A:F4:
+ CHECK_RESULT 0 0 0 'Display ipvlan mode info: failed!'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Display ipvlan mode info: failed!'
+ exit_mode=0
+ '[' -z '0 0 0 Display ipvlan mode info: failed!' ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ rmmod ipvlan
rmmod: ERROR: Module ipvlan is not currently loaded
+ CHECK_RESULT 1 0 0 'Remove ipvlan mode: failed!'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Remove ipvlan mode: failed!'
+ exit_mode=0
+ '[' -z '1 0 0 Remove ipvlan mode: failed!' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Remove ipvlan mode: failed!'
+ LOG_ERROR 'Remove ipvlan mode: failed!'
+ message='Remove ipvlan mode: failed!'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level error --message 'Remove ipvlan mode: failed!'
Mon Dec 23 07:09:12 2024 - ERROR - Remove ipvlan mode: failed!
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_IPVLAN_07.sh line 38'
+ message='oe_test_IPVLAN_07.sh line 38'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_IPVLAN_07.sh line 38'
Mon Dec 23 07:09:12 2024 - ERROR - oe_test_IPVLAN_07.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ lsmod
+ grep ipvlan
+ CHECK_RESULT 1 1 0 'ipvlan is not loaded after lsmod: failed!'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='ipvlan is not loaded after lsmod: failed!'
+ exit_mode=0
+ '[' -z '1 1 0 ipvlan is not loaded after lsmod: failed!' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon Dec 23 07:09:12 2024 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Dec 23 07:09:13 2024 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon Dec 23 07:09:13 2024 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp5jqotrka ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /home/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp5jqotrka
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /home/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon Dec 23 07:09:18 2024 - INFO  - End to restore the test environment.
